### ISSUE TITLE
download data

### ISSUE THREAD

**Issue by PigUnderRoof** [effiken/martin_et_al_cell_2019#1]
I try to download data by `make_martin_et_al_figures("martin_et_al_cell_2019/",download_data = T)`， but it doesn't work. Is there a solutionto this problem?
The warning message is 
`
Downloading file 1/4
trying URL 'https://www.dropbox.com/s/v0fr7pejzfynmbr/model_and_samples_ileum.rd?dl=1'
Error in download.file("https://www.dropbox.com/s/v0fr7pejzfynmbr/model_and_samples_ileum.rd?dl=1",  :
  cannot open URL 'https://www.dropbox.com/s/v0fr7pejzfynmbr/model_and_samples_ileum.rd?dl=1'
In addition: Warning message:
In download.file("https://www.dropbox.com/s/v0fr7pejzfynmbr/model_and_samples_ileum.rd?dl=1",  :
  URL 'https://www.dropbox.com/s/v0fr7pejzfynmbr/model_and_samples_ileum.rd?dl=1': status was 'Couldn't connect to s          erver'
`

**Comment by effiken** [comment]
Hi @PigUnderRoof, Sorry for the late response. Do you still encounter this problem? Download is working well for me now.

**Comment by PigUnderRoof** [comment]
Hi @effiken , it works, thanks!
